### ISSUE TITLE
Missing commit history

### ISSUE THREAD

**Issue by mr-mcox** [nschloe/colorio#193]
As of March 18th, it appears that there's only one file in the repository and it's the ReadMe. The commit history also appears to have disappeared (only one commit). Was this intentional? Has this project moved to another location?

**Comment by nschloe** [comment]
I'm reorganizing some of my workflows atm. Everything should continue to work as usual though.

**Comment by jrus** [comment]
I don’t really understand. It seems like "reorganizing my workflows" means "wiping out the project and associated community". Or am I missing something?

**Comment by shankarsivarajan** [comment]
> Or am I missing something?

You were.

**Comment by nschloe** [comment]
Although I got into color science a bit by accident, I love working in the field. 
Unfortunately, I never got paid for it, and I can no longer afford spending time. That's why I'm trying to move the project into the "professional" pay of my workday. Putting out the offer to donate didn't do _anything_ for color science, so the next step for me is to make it available at a small price. If this is something you cannot afford, feel free to contact me and we'll find a way!
